version: '3.8'

services:

#Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /Users/sonny/smart-brain-api
    environment:
      POSTGRES_URI: postgres://user:password@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    ports: 
      - "3000:3000"
    volumes:
      - ./:/Users/sonny/smart-brain-api

#Postgres
  postgres:
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: smart-brain-docker
        POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
      - "5432:5432"

#Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379" 
